spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_njober
    username: root
    password: 165842

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHadfjdkfjksdjfklsjflksdjklsdfjksdfjksldfjgjgggglel

